apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: traefik-vault-transport
spec:
  serverName: "vault"
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vault-route
spec:
  entryPoints:
    - websecure
  tls:
    secretName: tls-certificate
  routes:
    - match: Host(`vault.matiix310.dev`)
      kind: Rule
      services:
        - name: vault
          port: 443
          scheme: https
          serversTransport: traefik-vault-transport
